import { ReactNode } from "react";

export type SliderProps = {
  Id: string;
  GroupSlider: string;
  Title: null | string;
  URL: string;
  File: string;
  Description: string;
  Type: string;
  SiteId: string;
  Status: string;
  Sorting: string;
  CreatedDate: string;
  Creator: string;
  ModifierDate: string;
  Modifier: string;
  FileType: string;
};

export type KomoditasProps = {
  beda: ReactNode;
  price_now: any;
  kondisi: string;
  name: string | undefined;
  image: any;
  komoditi: string;
  id: string;
  price_today: string;
  price_yesterday: string;
  selisih: string;
};

export type LayananProps = {
  content_id: string;
  type_id: string;
  JenisLayanan: null | string;
  title: string;
  template_id: null | string;
  category_id: string;
  content: string;
  urlcontent: string;
  author: string;
  sumber_informasi: string;
  lampiran: null | string;
  uploaddokumen: string;
  jenis_lampiran: null | string;
  status: string;
  slug_title: string;
  organisasi_id: string;
  ParentId: null | string;
  ref_id: null | string;
  tgl_publish: string;
  created_at: string;
  updated_at: string;
  site_id: string;
  SiteName: string;
  DomainSite: string;
  Kanal: string;
  Category: string;
  Author: string;
  TypeLayanan: null | string;
};

export type LayananKotaProps = {
  Id: string;
  TypeId: string;
  Code: string;
  TitleMenu: string;
  SlugTitle: string;
  URLMenu: string;
  ImageMenu: null | string;
  Description: string;
  CategoryGroup: null | string;
  GroupId: string;
  IdGrup: string;
  ParentId: string;
  LevelMenu: null | string;
  SiteId: string;
  CreateDate: string;
  Creator: string;
  ModifyDate: string;
  Modifier: string;
};

export type InfografisProps = {
  Title: string;
  Attachment: boolean;
  id: string;
  name: string | null;
  image: string;
  status: string;
  URL: string;
  created_at: string;
  updated_at: string;
  FileType: string;
  Type: string;
};

export type PengumumanProps = {
  image: string | undefined;
  content_id: string;
  type_id: string;
  JenisLayanan: null | string;
  title: string;
  template_id: null | string;
  category_id: string;
  content: string;
  urlcontent: string;
  author: string;
  sumber_informasi: string;
  lampiran?: null | string | any;
  uploaddokumen: null | string;
  jenis_lampiran: null | string;
  status: string;
  slug_title: string;
  organisasi_id: string;
  ParentId: null | string;
  ref_id: null | string;
  tgl_publish: string;
  created_at: string;
  updated_at: string;
  site_id: string;
  SiteName: string;
  DomainSite: string;
  Kanal: string;
  Category: null | string;
  Author: string;
  TypeLayanan: null | string;
};

export type DokumenProps = {
  content_id: string;
  type_id: string;
  JenisLayanan: null | string;
  title: string;
  template_id: null | string;
  category_id: string;
  content: string;
  urlcontent: string;
  author: string;
  sumber_informasi: string;
  lampiran: null | string;
  uploaddokumen: string;
  jenis_lampiran: null | string;
  status: string;
  slug_title: string;
  organisasi_id: string;
  ParentId: null | string;
  ref_id: null | string;
  tgl_publish: string;
  created_at: string;
  updated_at: string;
  site_id: string;
  SiteName: string;
  DomainSite: string;
  Kanal: string;
  Category: string;
  Author: string;
  TypeLayanan: null | string;
};

export type PotensiProps = {
  Id: string;
  SiteId: string;
  TypeId: string;
  Nama: string;
  Image: string;
  Alamat: string;
  Lat: string;
  Lng: string;
  Deskripsi: string;
  Mobile: null | string;
  Telp: string;
  PJ: string;
  Facebook: string;
  Instagram: string;
  Web: string;
  Email: string;
  Type: string;
};

export type BeritaKotaProps = {
  slug_title: any;
  lampiran: any;
  SiteName: ReactNode;
  created_at: ReactNode;
  content: any;
  title: string;
  published_at: string;
  thumb: string;
  description: string;
  body: string;
  slug: string;
  image: string;
  link: string;
};

export type BeritaProps = {
  content_id: string;
  type_id: string;
  JenisLayanan: null | string;
  title: string;
  template_id: null | string;
  category_id: string;
  content: string;
  urlcontent: string;
  author: string;
  sumber_informasi: string;
  lampiran: string;
  uploaddokumen: null | string;
  jenis_lampiran: null | string;
  status: string;
  slug_title: string;
  organisasi_id: string;
  ParentId: null | string;
  ref_id: null | string;
  tgl_publish: string;
  created_at: string;
  updated_at: string;
  site_id: string;
  SiteName: string;
  DomainSite: string;
  Kanal: string;
  Category: string;
  Author: string;
  TypeLayanan: null | string;
};

export type BeritaKelurahanProps = {
  content_id: string;
  type_id: string;
  JenisLayanan: null | string;
  title: string;
  template_id: null | string;
  category_id: string;
  content: string;
  urlcontent: string;
  author: string;
  sumber_informasi: string;
  lampiran: null | string;
  uploaddokumen: null | string;
  jenis_lampiran: null | string;
  status: string;
  slug_title: string;
  organisasi_id: string;
  ParentId: null | string;
  ref_id: null | string;
  tgl_publish: string;
  created_at: string;
  updated_at: string;
  site_id: string;
  SiteName: string;
  DomainSite: string;
  Kanal: string;
  Category: null | string;
  Author: string;
  TypeLayanan: null | string;
};
