export type StandarLayananProps = {
  content_id: string;
  type_id: string;
  JenisLayanan: null | string;
  title: string;
  template_id: null | string;
  category_id: string;
  content: string;
  urlcontent: string;
  author: string;
  sumber_informasi: string;
  lampiran: null | string;
  uploaddokumen: string;
  jenis_lampiran: null | string;
  status: string;
  slug_title: string;
  organisasi_id: string;
  ParentId: null | string;
  ref_id: null | string;
  tgl_publish: string;
  created_at: string;
  updated_at: string;
  site_id: string;
  SiteName: string;
  DomainSite: string;
  Kanal: string;
  Category: string;
  Author: string;
  TypeLayanan: null | string;
};

export type ListStandarPelayananProps = {
  content_id: string;
  type_id: string;
  JenisLayanan: string | null;
  title: string;
  template_id: string | null;
  category_id: string;
  content: string;
  urlcontent: string;
  author: string;
  sumber_informasi: string;
  lampiran: string | null;
  uploaddokumen: string;
  jenis_lampiran: string | null;
  status: string;
  slug_title: string;
  organisasi_id: string;
  ParentId: string | null;
  ref_id: string | null;
  tgl_publish: string;
  created_at: string;
  updated_at: string;
  site_id: string;
  SiteName: string;
  DomainSite: string;
  Kanal: string;
  Category: string;
  Author: string;
  TypeLayanan: string | null;
};


export type LayananKotaProps = {
  Id: string;
  TypeId: string;
  Code: string;
  TitleMenu: string;
  SlugTitle: string;
  URLMenu: string;
  ImageMenu: null | string;
  Description: string;
  CategoryGroup: null | string;
  GroupId: string;
  IdGrup: string;
  ParentId: string;
  LevelMenu: null | string;
  SiteId: string;
  CreateDate: string;
  Creator: string;
  ModifyDate: string;
  Modifier: string;
};

export type FaqProps = {
  content_id: string;
  type_id: string;
  JenisLayanan: null | string;
  title: string;
  template_id: null | string;
  category_id: string;
  content: string;
  urlcontent: string;
  author: string;
  sumber_informasi: string;
  lampiran: null | string;
  uploaddokumen: null | string;
  jenis_lampiran: null | string;
  status: string;
  slug_title: string;
  organisasi_id: string;
  ParentId: null | string;
  ref_id: null | string;
  tgl_publish: string;
  created_at: string;
  updated_at: string;
  site_id: string;
  SiteName: string;
  DomainSite: string;
  Kanal: string;
  Category: string;
  Author: string;
  TypeLayanan: null | string;
};
